/**
 * utils/quoteData.js - 今日名言数据
 * 
 * 包含：
 * - QUOTE_FIELDS: 名言分类配置
 * - FAMOUS_QUOTES: 名家名言库（100条）
 */

const QUOTE_FIELDS = [
  { id: 'poetry', name: '古诗词', icon: '📜' },
  { id: 'modern', name: '现代名言', icon: '💬' },
  { id: 'foreign', name: '外国名言', icon: '📚' },
  { id: 'wisdom', name: '人生哲理', icon: '✨' },
]

// 名家名言库（100条）
const FAMOUS_QUOTES = [
  // 古诗词（50条）
  { text: '春江潮水连海平，海上明月共潮生。', author: '张若虚', work: '《春江花月夜》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '大漠孤烟直，长河落日圆。', author: '王维', work: '《使至塞上》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '采菊东篱下，悠然见南山。', author: '陶渊明', work: '《饮酒·其五》', domainName: '田园诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '人生若只如初见，何事秋风悲画扇。', author: '纳兰性德', work: '《木兰花令》', domainName: '清词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '问君能有几多愁？恰似一江春水向东流。', author: '李煜', work: '《虞美人》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '但愿人长久，千里共婵娟。', author: '苏轼', work: '《水调歌头》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '人生自古谁无死？留取丹心照汗青。', author: '文天祥', work: '《过零丁洋》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '山重水复疑无路，柳暗花明又一村。', author: '陆游', work: '《游山西村》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '会当凌绝顶，一览众山小。', author: '杜甫', work: '《望岳》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '长风破浪会有时，直挂云帆济沧海。', author: '李白', work: '《行路难》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '海内存知己，天涯若比邻。', author: '王勃', work: '《送杜少府之任蜀州》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '欲穷千里目，更上一层楼。', author: '王之涣', work: '《登鹳雀楼》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '落霞与孤鹜齐飞，秋水共长天一色。', author: '王勃', work: '《滕王阁序》', domainName: '骈文', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '不以物喜，不以己悲。', author: '范仲淹', work: '《岳阳楼记》', domainName: '散文', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '先天下之忧而忧，后天下之乐而乐。', author: '范仲淹', work: '《岳阳楼记》', domainName: '散文', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '明月松间照，清泉石上流。', author: '王维', work: '《山居秋暝》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '独在异乡为异客，每逢佳节倍思亲。', author: '王维', work: '《九月九日忆山东兄弟》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '劝君更尽一杯酒，西出阳关无故人。', author: '王维', work: '《送元二使安西》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '黄沙百战穿金甲，不破楼兰终不还。', author: '王昌龄', work: '《从军行》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '秦时明月汉时关，万里长征人未还。', author: '王昌龄', work: '《出塞》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '忽如一夜春风来，千树万树梨花开。', author: '岑参', work: '《白雪歌送武判官归京》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '月落乌啼霜满天，江枫渔火对愁眠。', author: '张继', work: '《枫桥夜泊》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '春风又绿江南岸，明月何时照我还。', author: '王安石', work: '《泊船瓜洲》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '不畏浮云遮望眼，自缘身在最高层。', author: '王安石', work: '《登飞来峰》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '此情可待成追忆，只是当时已惘然。', author: '李商隐', work: '《锦瑟》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '身无彩凤双飞翼，心有灵犀一点通。', author: '李商隐', work: '《无题》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '春蚕到死丝方尽，蜡炬成灰泪始干。', author: '李商隐', work: '《无题》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '纸上得来终觉浅，绝知此事要躬行。', author: '陆游', work: '《冬夜读书示子聿》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '夜阑卧听风吹雨，铁马冰河入梦来。', author: '陆游', work: '《十一月四日风雨大作》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '王师北定中原日，家祭无忘告乃翁。', author: '陆游', work: '《示儿》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '出师未捷身先死，长使英雄泪满襟。', author: '杜甫', work: '《蜀相》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '安得广厦千万间，大庇天下寒士俱欢颜。', author: '杜甫', work: '《茅屋为秋风所破歌》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '无边落木萧萧下，不尽长江滚滚来。', author: '杜甫', work: '《登高》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '天生我材必有用，千金散尽还复来。', author: '李白', work: '《将进酒》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '仰天大笑出门去，我辈岂是蓬蒿人。', author: '李白', work: '《南陵别儿童入京》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '抽刀断水水更流，举杯消愁愁更愁。', author: '李白', work: '《宣州谢朓楼饯别校书叔云》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '飞流直下三千尺，疑是银河落九天。', author: '李白', work: '《望庐山瀑布》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '曾经沧海难为水，除却巫山不是云。', author: '元稹', work: '《离思》', domainName: '唐诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '问渠那得清如许？为有源头活水来。', author: '朱熹', work: '《观书有感》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '莫听穿林打叶声，何妨吟啸且徐行。', author: '苏轼', work: '《定风波》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。', author: '苏轼', work: '《定风波》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '回首向来萧瑟处，归去，也无风雨也无晴。', author: '苏轼', work: '《定风波》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '横看成岭侧成峰，远近高低各不同。', author: '苏轼', work: '《题西林壁》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '不识庐山真面目，只缘身在此山中。', author: '苏轼', work: '《题西林壁》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '欲把西湖比西子，淡妆浓抹总相宜。', author: '苏轼', work: '《饮湖上初晴后雨》', domainName: '宋诗', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '十年生死两茫茫，不思量，自难忘。', author: '苏轼', work: '《江城子》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '人有悲欢离合，月有阴晴圆缺，此事古难全。', author: '苏轼', work: '《水调歌头》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '大江东去，浪淘尽，千古风流人物。', author: '苏轼', work: '《念奴娇·赤壁怀古》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '天行健，君子以自强不息。', author: '《周易》', work: '', domainName: '易经', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '地势坤，君子以厚德载物。', author: '《周易》', work: '', domainName: '易经', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '穷则变，变则通，通则久。', author: '《周易》', work: '', domainName: '易经', domainIcon: '📜', era: 'ancient', region: 'china' },
  // 现代/外国名言（50条）
  { text: '世界以痛吻我，要我报之以歌。', author: '泰戈尔', work: '《飞鸟集》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '生如夏花之绚烂，死如秋叶之静美。', author: '泰戈尔', work: '《飞鸟集》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '当你为错过太阳而哭泣，你也要错过群星了。', author: '泰戈尔', work: '《飞鸟集》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '天空没有留下翅膀的痕迹，但我已经飞过。', author: '泰戈尔', work: '《飞鸟集》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '眼睛为她下着雨，心却为她打着伞，这就是爱情。', author: '泰戈尔', work: '《吉檀迦利》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '知识就是力量。', author: '培根', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '读一本好书，就是和许多高尚的人谈话。', author: '歌德', work: '', domainName: '文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '谁若游戏人生，他就一事无成。', author: '歌德', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '你若盛开，蝴蝶自来。', author: '泰戈尔', work: '《飞鸟集》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '冬天已经到来，春天还会远吗？', author: '雪莱', work: '《西风颂》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '走自己的路，让别人说去吧。', author: '但丁', work: '《神曲》', domainName: '外国文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '成功的秘诀，在永不改变既定的目的。', author: '卢梭', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '人的差异在于业余时间。', author: '爱因斯坦', work: '', domainName: '科学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '想象力比知识更重要。', author: '爱因斯坦', work: '', domainName: '科学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '天才是1%的灵感加99%的汗水。', author: '爱迪生', work: '', domainName: '发明家', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '失败乃成功之母。', author: '爱迪生', work: '', domainName: '发明家', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '自助者，天助之。', author: '品达', work: '', domainName: '古希腊', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '人生最终的价值在于觉醒和思考的能力。', author: '亚里士多德', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '幸福是把灵魂安放在最适当的位置。', author: '亚里士多德', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '给我一个支点，我可以撬起整个地球。', author: '阿基米德', work: '', domainName: '科学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '活着就是为了改变世界。', author: '乔布斯', work: '', domainName: '科技', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: 'Stay hungry, stay foolish.', author: '乔布斯', work: '斯坦福演讲', domainName: '科技', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '我唯一知道的就是自己一无所知。', author: '苏格拉底', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '认识你自己。', author: '苏格拉底', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '未经审视的人生不值得过。', author: '苏格拉底', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '世上只有一种英雄主义，就是认清生活真相后依然热爱生活。', author: '罗曼·罗兰', work: '《米开朗琪罗》', domainName: '文学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '当你凝视深渊时，深渊也在凝视你。', author: '尼采', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '那些杀不死你的，终将使你更强大。', author: '尼采', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '每一个不曾起舞的日子，都是对生命的辜负。', author: '尼采', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '我思故我在。', author: '笛卡尔', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '你的时间有限，不要浪费于重复别人的生活。', author: '乔布斯', work: '', domainName: '科技', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '地上本没有路，走的人多了，也便成了路。', author: '鲁迅', work: '《故乡》', domainName: '现代文学', domainIcon: '📚', era: 'modern', region: 'china' },
  { text: '横眉冷对千夫指，俯首甘为孺子牛。', author: '鲁迅', work: '《自嘲》', domainName: '现代文学', domainIcon: '📚', era: 'modern', region: 'china' },
  { text: '时间就像海绵里的水，只要愿挤，总还是有的。', author: '鲁迅', work: '', domainName: '现代文学', domainIcon: '📚', era: 'modern', region: 'china' },
  { text: '希望是附丽于存在的，有存在，便有希望。', author: '鲁迅', work: '', domainName: '现代文学', domainIcon: '📚', era: 'modern', region: 'china' },
  { text: '真的猛士，敢于直面惨淡的人生。', author: '鲁迅', work: '《记念刘和珍君》', domainName: '现代文学', domainIcon: '📚', era: 'modern', region: 'china' },
  { text: '生命在于运动。', author: '伏尔泰', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '我不同意你的观点，但我誓死捍卫你说话的权利。', author: '伏尔泰', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '使人疲惫的不是远方的高山，而是鞋子里的一粒沙子。', author: '伏尔泰', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '存在即合理。', author: '黑格尔', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '一个民族有一群仰望星空的人，他们才有希望。', author: '黑格尔', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '没有所谓命运这个东西，一切无非是考验、惩罚或补偿。', author: '伏尔泰', work: '', domainName: '哲学', domainIcon: '📚', era: 'modern', region: 'foreign' },
  { text: '人生如梦，一尊还酹江月。', author: '苏轼', work: '《念奴娇》', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '人生没有白走的路，每一步都算数。', author: '李宗盛', work: '', domainName: '歌词', domainIcon: '🎵', era: 'modern', region: 'china' },
  { text: '愿你出走半生，归来仍是少年。', author: '苏轼', work: '《定风波》化用', domainName: '宋词', domainIcon: '📜', era: 'ancient', region: 'china' },
  { text: '不忘初心，方得始终。', author: '《华严经》', work: '', domainName: '佛学', domainIcon: '📿', era: 'ancient', region: 'china' },
  { text: '活在当下。', author: '一行禅师', work: '', domainName: '禅学', domainIcon: '📿', era: 'modern', region: 'foreign' },
  { text: '不是看到希望才坚持，而是坚持了才看到希望。', author: '无名', work: '', domainName: '励志', domainIcon: '💪', era: 'modern', region: 'china' },
  { text: '所有的伟大，都源于一个勇敢的开始。', author: '无名', work: '', domainName: '励志', domainIcon: '💪', era: 'modern', region: 'china' },
  { text: '生活不是等待风暴过去，而是学会在雨中跳舞。', author: '无名', work: '', domainName: '励志', domainIcon: '💪', era: 'modern', region: 'foreign' },
]

module.exports = {
  QUOTE_FIELDS,
  FAMOUS_QUOTES,
}
